services:
  webapp.student_list:
    image: php:apache
    container_name: webapp_student_list
    depends_on:
      - api_project
    ports:
      - "80:80"
    volumes:
      - ./website/:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
      - API_HOST=api_project
      - API_PORT=5000
    networks:
      - mini_project

  api_project:
    build: ./simple_api        # 👈 OBLIGATOIRE !
    image: api:v3              # Nom local de l'image
    container_name: api_project
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    expose:
      - "5000"
    networks:
      - mini_project

networks:
  mini_project:
    driver: bridge

